language: node_js

node_js:
- 'node'

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
  fi

install:
  - yarn install

script:
  - yarn run tslint
  - yarn run compile
  - yarn vscode:prepublish
  - yarn test --silent